name: Deploy to GCP

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        service_account_key: ${{ secrets.GCP_AUTH }}
    - run: gcloud info
