name: Test
on:
  pull_request:
    branches:
      - master
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: go/src/website

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
      env:
        GOPATH: /home/runner/work/website/go

    - name: Lint
      run: |
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0
        $GOPATH/bin/golangci-lint run
      env:
        GOPATH: /home/runner/work/website/go

    - name: Test
      run: go test
      env:
        GOPATH: /home/runner/work/website/go
